### ISSUE TITLE
Fix Intermittent failing test

### ISSUE THREAD

**Issue by markglh** [WW-Digital/reactive-kinesis#10]
Sometime (in Travis) the following test fails:

```
[info]   - When the response is a failed batch it should shutdown and stop processing *** FAILED ***
[info]     org.mockito.exceptions.verification.WantedButNotInvoked: Wanted but not invoked:
[info] worker.requestShutdown();
[info] -> at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anon$2.$anonfun$new$7(ConsumerProcessingManagerSpec.scala:162)
[info] 
[info] However, there was exactly 1 interaction with this mock:
[info] worker.getApplicationName();
[info] -> at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManager.<init>(ConsumerProcessingManager.scala:65)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anon$2.$anonfun$new$7(ConsumerProcessingManagerSpec.scala:162)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anon$2$$Lambda$2021/1019640917.apply(Unknown Source)
[info]     at org.scalatest.concurrent.Futures.whenReady(Futures.scala:677)
[info]     at org.scalatest.concurrent.Futures.whenReady$(Futures.scala:675)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec.whenReady(ConsumerProcessingManagerSpec.scala:52)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anon$2.<init>(ConsumerProcessingManagerSpec.scala:156)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec.$anonfun$new$6(ConsumerProcessingManagerSpec.scala:152)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$Lambda$1999/696904565.apply(Unknown Source)
[info]     at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]     ...
```

https://travis-ci.org/WW-Digital/reactive-kinesis/jobs/237901638

**Comment by markglh** [comment]
Reopening this, saw it again in travis:
```
[info]   - When the response is a failed batch it should shutdown and stop processing *** FAILED ***
[info]     org.mockito.exceptions.verification.WantedButNotInvoked: Wanted but not invoked:
[info] worker.startGracefulShutdown();
[info] -> at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5$$anon$2$$anonfun$5.apply(ConsumerProcessingManagerSpec.scala:163)
[info] 
[info] However, there was exactly 1 interaction with this mock:
[info] worker.getApplicationName();
[info] -> at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManager.<init>(ConsumerProcessingManager.scala:65)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5$$anon$2$$anonfun$5.apply(ConsumerProcessingManagerSpec.scala:163)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5$$anon$2$$anonfun$5.apply(ConsumerProcessingManagerSpec.scala:154)
[info]     at org.scalatest.concurrent.Futures$class.whenReady(Futures.scala:677)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec.whenReady(ConsumerProcessingManagerSpec.scala:52)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5$$anon$2.<init>(ConsumerProcessingManagerSpec.scala:154)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5.apply(ConsumerProcessingManagerSpec.scala:152)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5.apply(ConsumerProcessingManagerSpec.scala:152)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
```
