### ISSUE TITLE
ConsumerProcessingManagerSpec random failed test

### ISSUE THREAD

**Issue by fernando-oktana** [WW-Digital/reactive-kinesis#17]
Fix random fail in test:
ConsumerProcessingManagerSpec

 - When the response is a failed batch it should shutdown and stop processing *** FAILED ***
[info]     org.mockito.exceptions.verification.WantedButNotInvoked: Wanted but not invoked:
[info] worker.requestShutdown();
[info] -> at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anon$2.$anonfun$new$7(ConsumerProcessingManagerSpec.scala:162)
[info]
[info] However, there was exactly 1 interaction with this mock:
[info] worker.getApplicationName();

[info] -> at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManager.<init>(ConsumerProcessingManager.scala:65)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anon$2.$anonfun$new$7(ConsumerProcessingManagerSpec.scala:162)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anon$2$$Lambda$327/1114273098.apply(Unknown Source)
[info]     at org.scalatest.concurrent.Futures.whenReady(Futures.scala:677)
[info]     at org.scalatest.concurrent.Futures.whenReady$(Futures.scala:675)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec.whenReady(ConsumerProcessingManagerSpec.scala:52)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$anon$2.<init>(ConsumerProcessingManagerSpec.scala:156)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec.$anonfun$new$6(ConsumerProcessingManagerSpec.scala:152)
[info]     at com.weightwatchers.reactive.kinesis.consumer.ConsumerProcessingManagerSpec$$Lambda$240/1621586683.apply(Unknown Source)
[info]     at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)

**Comment by fernando-oktana** [comment]
duplicated
