### ISSUE TITLE
creating a CWPublisherRunnable that tries to publish to cloudwatch

### ISSUE THREAD

**Issue by fommil** [WW-Digital/reactive-kinesis#55]
I've been debugging an issue where `MetricsLevel = none` is being ignored. No matter what is used, runtime logs are full of `CWPublisherRunnable` stuff like this (keep reading beyond the stack trace, I have some analysis)

```
Could not publish 13 datums to CloudWatch

c.a.s.c.m.AmazonCloudWatchException: The security token included in the request is invalid. (Service: AmazonCloudWatch; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: f4de4145-0db8-11e8-97f0-5b84c3ea3332)
    at c.a.h.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
    at c.a.h.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
    at c.a.h.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
    at c.a.h.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
    at c.a.h.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
    at c.a.h.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
    at c.a.h.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
    at c.a.h.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
    at c.a.h.AmazonHttpClient.execute(AmazonHttpClient.java:513)
    at c.a.s.c.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:1325)
    at c.a.s.c.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:1301)
    at c.a.s.c.AmazonCloudWatchClient.executePutMetricData(AmazonCloudWatchClient.java:1209)
    at c.a.s.c.AmazonCloudWatchClient.putMetricData(AmazonCloudWatchClient.java:1186)
    at c.a.s.k.m.i.DefaultCWMetricsPublisher.publishMetrics(DefaultCWMetricsPublisher.java:63)
    at c.a.s.k.m.i.CWPublisherRunnable.runOnce(CWPublisherRunnable.java:144)
    at c.a.s.k.m.i.CWPublisherRunnable.run(CWPublisherRunnable.java:90)
    at java.lang.Thread.run(Thread.java:748)
```

I put together a monkey patch version of `CWPublisherRunnable` that dumps out the stack trace when the runnable is created and it looks like the culprit is `com.weightwatchers.reactive.kinesis.consumer.KinesisConsumer.$anonfun$start$2(KinesisConsumer.scala:259)`

```
java.lang.Exception
	at com.amazonaws.services.kinesis.metrics.impl.CWPublisherRunnable.<init>(CWPublisherRunnable.java:71)
	at com.amazonaws.services.kinesis.metrics.impl.CWPublisherRunnable.<init>(CWPublisherRunnable.java:63)
	at com.amazonaws.services.kinesis.metrics.impl.CWMetricsFactory.<init>(CWMetricsFactory.java:131)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker$WorkerCWMetricsFactory.<init>(Worker.java:1043)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.getMetricsFactory(Worker.java:1020)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.access$500(Worker.java:66)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker$Builder.build(Worker.java:1254)
	at com.weightwatchers.reactive.kinesis.consumer.KinesisConsumer.kclWorker$lzycompute(KinesisConsumer.scala:230)
	at com.weightwatchers.reactive.kinesis.consumer.KinesisConsumer.kclWorker(KinesisConsumer.scala:228)
	at com.weightwatchers.reactive.kinesis.consumer.KinesisConsumer.$anonfun$start$2(KinesisConsumer.scala:259)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by fommil** [comment]
this looks like it might be fixed in 1.9.1 of the amazon lib
